# Generated by Yazelix
# Timestamp: 2026-02-13 08:35:28 -03:00
# Source: /home/lucca/.local/share/yazelix/configs/terminal_emulators
-- WezTerm configuration for Yazelix
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.default_prog = {'sh', '-c', 'exec $HOME/.config/yazelix/shells/posix/start_yazelix.sh'}
config.window_decorations = "NONE"
config.window_padding = { left = 0, right = 0, top = 10, bottom = 0 }
config.color_scheme = 'Abernathy'

-- Hide tab bar (Zellij handles tabs)
config.enable_tab_bar = false

-- Transparency (configurable via yazelix.toml)
config.window_background_opacity = 0.85

-- Cursor trails: Not supported in WezTerm

return config